#cloud-config
package_update: true
package_upgrade: true

packages:
  - wireguard

# set the locale
locale: en_US.UTF-8

# timezone: set the timezone for this instance
timezone: UTC

# final_message: "System boot (via cloud-init) finished at $TIMESTAMP. Up $UPTIME seconds"

